# Generated by Django 5.1.4 on 2026-04-12 21:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emr', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('VOID', 'Void / Cancelled')], default='DRAFT', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('QRIS', 'QRIS'), ('TRANSFER', 'Bank Transfer'), ('CARD', 'Debit / Credit Card'), ('SPLIT', 'Split Payment')], max_length=10)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transfer ref, QRIS transaction ID, card last 4', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.branch')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='emr.consultation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Auto-filled from item name; editable', max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=0, help_text='Price at time of sale — snapshot, not live', max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=14)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'branch'], name='billing_inv_status_8df87f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='billing_inv_created_1e16da_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx'),
        ),
    ]
