# Generated by Django 5.1.4 on 2026-04-12 21:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subjective', models.TextField(blank=True, help_text='Owner complaint, history, presenting signs')),
                ('objective', models.TextField(blank=True, help_text='Vitals, physical exam findings')),
                ('assessment', models.TextField(blank=True, help_text='Diagnosis / differential diagnoses')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan, prescriptions, follow-up instructions')),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capillary_refill_time', models.CharField(blank=True, max_length=20)),
                ('mucous_membrane_color', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open — editing allowed'), ('CLOSED', 'Closed — read only'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking — increment on every save to detect conflicts')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only notes — not visible to client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment')),
                ('attending_vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='core.branch')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='emr/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('PHOTO', 'Clinical Photo'), ('LAB', 'Lab Result'), ('XRAY', 'X-Ray / DICOM'), ('DOC', 'Document'), ('VIDEO', 'Video')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_device', models.CharField(blank=True, help_text='X-Device-ID header — useful for multi-device audit', max_length=50)),
                ('is_from_camera', models.BooleanField(default=False, help_text='True when captured directly from device camera')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emr.consultation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Attachment',
                'verbose_name_plural': 'Medical Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g. 5mg/kg, 1 tablet', max_length=200)),
                ('frequency', models.CharField(help_text='e.g. Twice daily, Every 8 hours', max_length=100)),
                ('duration_days', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_controlled_drug', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='emr.consultation')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='inventory.inventoryitem')),
                ('witnessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'visit_date'], name='emr_consult_patient_b488c4_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['branch', 'status'], name='emr_consult_branch__bceb91_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['attending_vet', 'visit_date'], name='emr_consult_attendi_d3e644_idx'),
        ),
    ]
