# Generated by Django 5.1.4 on 2026-04-12 21:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, help_text='Generic / INN name for medicines', max_length=200)),
                ('category', models.CharField(choices=[('MED', 'Medicine'), ('VACCINE', 'Vaccine'), ('SUPPLY', 'Medical Supply'), ('FOOD', 'Pet Food'), ('GROOMING', 'Grooming Product'), ('RETAIL', 'Retail Item'), ('SERVICE', 'Service (non-stock)')], max_length=10)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('unit', models.CharField(default='unit', help_text='e.g. tablet, ml, bottle, bag', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=0, help_text='Purchase/cost price in IDR', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=0, help_text='Retail selling price in IDR', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax percentage e.g. 11.00 for 11% PPN', max_digits=5)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Trigger low-stock alert when quantity drops to this level', max_digits=10)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('is_controlled_drug', models.BooleanField(default=False, help_text='Requires witnessed prescription and double-check')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('avg_daily_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('predicted_stockout_date', models.DateField(blank=True, null=True)),
                ('restock_recommendation', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='core.branch')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase / Received'), ('SALE', 'Sold via Invoice'), ('ADJUSTMENT', 'Manual Adjustment'), ('EXPIRED', 'Expired / Disposed'), ('RETURN', 'Client Return'), ('TRANSFER', 'Branch Transfer'), ('VACCINE_USE', 'Used in Vaccination')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive = in, Negative = out', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(blank=True, help_text='Invoice number, PO number, or adjustment ID', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch', 'category', 'is_active'], name='inventory_i_branch__f58954_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__69d012_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item', 'transaction_type', 'created_at'], name='inventory_s_item_id_b7f424_idx'),
        ),
    ]
