# Generated by Django 5.1.4 on 2026-04-12 21:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RABBIT', 'Rabbit'), ('BIRD', 'Bird'), ('REPTILE', 'Reptile'), ('HAMSTER', 'Hamster'), ('EXOTIC', 'Exotic / Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MN', 'Male (Neutered)'), ('FS', 'Female (Spayed)')], max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('microchip_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('current_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('photo', models.ImageField(blank=True, upload_to='patients/photos/%Y/%m/')),
                ('qr_code', models.ImageField(blank=True, upload_to='patients/qr/')),
                ('known_allergies', models.TextField(blank=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('is_deceased', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clients.client')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('administered_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_given', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, help_text='Vaccine product — auto-deducts from stock when saved', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['owner', 'is_active'], name='patients_pa_owner_i_61695d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['species'], name='patients_pa_species_2e2a23_idx'),
        ),
    ]
