# Generated by Django 5.1.4 on 2026-04-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number if different from phone', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('id_number', models.CharField(blank=True, help_text='KTP / Passport number', max_length=20)),
                ('preferred_contact', models.CharField(choices=[('WA', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('PHONE', 'Phone Call')], default='WA', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='VIP notes, preferences, allergies to communicate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.branch')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx'), models.Index(fields=['last_name', 'first_name'], name='clients_cli_last_na_198e2f_idx'), models.Index(fields=['branch', 'is_active'], name='clients_cli_branch__13d832_idx')],
                'unique_together': {('branch', 'phone')},
            },
        ),
    ]
