# Generated by Django 5.1.4 on 2026-04-12 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('appointment_type', models.CharField(choices=[('CONSULT', 'Consultation'), ('VACCINE', 'Vaccination'), ('GROOM', 'Grooming'), ('SURGERY', 'Surgery'), ('FOLLOWUP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('BOARDING', 'Boarding Check-in')], max_length=15)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['branch', 'scheduled_at'], name='appointment_branch__8dba96_idx'), models.Index(fields=['veterinarian', 'scheduled_at'], name='appointment_veterin_a8ae19_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['BOOKED', 'CONFIRMED', 'IN_PROGRESS'])), fields=('veterinarian', 'scheduled_at'), name='unique_vet_timeslot')],
            },
        ),
    ]
